development:
  adapter: postgresql
  encoding: unicode
  database: dex-rails-development
  pool: 150
  timeout: 5000

# test:
#   <<: *default
#   database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 150
  timeout: 5000


