default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  prepared_statements: false
  advisory_locks: false

development:
  <<: *default
  database: dex-rails-development
  adapter: postgresql
  encoding: unicode

test:
  <<: *default
  database: dex-rails-test
  adapter: postgresql

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>

