development:
  adapter: postgresql
  encoding: unicode
  database: dex-rails-development
  pool: 25
  timeout: 5000
  prepared_statements: false
  advisory_locks: false

# test:
#   <<: *default
#   database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 150
  timeout: 5000
  prepared_statements: false
  advisory_locks: false


