:concurrency: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
:queues:
  - [critical, 1024]
  - [crawling, 512]
  - [retry_crawling, 256]
  - [downloading, 64]
  - [retry_downloading, 32]
  - [persisting, 4]
  - [retry_persisting, 2]