:concurrency: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
:queues:
  - [indexing, 256]
  - [parsing, 8]
  - [downloading, 4]
  - [critical, 1024]
  - [persisting, 512]
  - [retry_persisting, 128]
  - [crawling, 8]
  - [retry_crawling, 1]
